# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "Linux Eğitimi"
email: info@linuxdersleri.net
description: "GNU/Linux için Türkçe içerik sağlamak üzere kurulmuş bir platformdur."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.linuxdersleri.net"
github_username:  linux-dersleri

# Build settings

plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-toc
  - kramdown


jekyll_timeago:
  depth: 1
  threshold: 1
  translations_path: "/data/tr.yml"
  default_locale: 'tr'
  available_locales:
    - 'tr'
 
toc:
  min_level: 1
  max_level: 6
  ordered_list: false
  no_toc_section_class: no_toc_section
  list_id: toc
  list_class: section-nav
  sublist_class: ''
  item_class: toc-entry
  item_prefix: <h
  
# Jekyll config
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  input: GFM
  auto_ids:       true
  toc_levels:     1..3
  
collections:
  authors:
    output: true
  kaynaklar:
    output: true
  egitim:
    output: true
  komut:
    output: true
  pagefind:
    output: true

defaults:
- scope:
    path: ''
    type: authors
  values:
    permalink: "/yazar/:name/"
    layout: author
    twitter:
- scope:
    path: ''
    type: kaynaklar
  values:
    permalink: "/kaynaklar/:title/"
    layout: title
    twitter:
- scope:
    path: ''
    type: egitim
  values:
    permalink: "/egitim/:categories/:title/"
    layout: title
    twitter:
- scope:
    path: ''
    type: komut
  values:
    permalink: "/komut/:title/"
    layout: title
    twitter:       

# Turkish Month
month_names:
  Jan: Oca
  Feb: Şub
  Mar: Mar
  Apr: Nis
  May: May
  Jun: Haz
  Jul: Tem
  Aug: Ağu
  Sep: Eyl
  Oct: Eki
  Nov: Kas
  Dec: Ara